Tunes package specs
On Summit and Peak:

- Adios2 +zfp gets built as a dependency for other packages under GCC
  and Clang compilers. As such, we make that the default general compute
  package spec and handle the special cases for toolchains that cannot
  build it separately. For toolchains that can build Adios2 with zfp
  support, zfp-disabled builds have their modulefiles blacklisted to
  facilitate modulefile tree regeneration without name conflics.
- Clang v10 cannot build muelu component of trilinos. Instead we build a
  trilinos without muelu support for that toolchains. See
  https://jira.ccs.ornl.gov/projects/OLCFSW/queues/custom/131/OLCFSW-12
  for details.
- Modulefile suffixes are added to Gromacs, Kokkos, and libfabric to
  facilitate modulefile tree regeneration without name conficts.
- Removes problem specs for GCC@10.2.0
  - rempi does not seem to include necessary headers for GCC10 to
    recognize the `string` type:
    ```
    rempi_message_manager.h:53:3: error: 'string' does not name a type; did you mean 'stdin'?
       53 |   string to_string();
          |   ^~~~~~
          |   stdin
    ```
  - Adios2 suffers undefined referenece errors building under GCC10:
    ```
    ../../lib64/libadios2_core.so.2.6.0: undefined reference to `int adios2::format::DataManSerializer::GetData<std::complex<double> >(std::complex<double>*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<unsigned long, std::allocator<unsigned long> > const&, std::vector<unsigned long, std::allocator<unsigned long> > const&, unsigned long, std::vector<unsigned long, std::allocator<unsigned long> > const&, std::vector<unsigned long, std::allocator<unsigned long> > const&)'
    collect2: error: ld returned 1 exit status
    make[2]: ***
    [source/utils/CMakeFiles/adios_reorganize.dir/build.make:137:
    bin/adios2_reorganize] Error 1
    make[2]: Leaving directory
    '/tmp/belhorn/spack-stage/spack-stage-adios2-2.6.0-xnwpiptern7e6z4mou5nhf3ksqe67y4d/spack-build-xnwpipt'
    make[1]: *** [CMakeFiles/Makefile2:1458:
    source/utils/CMakeFiles/adios_reorganize.dir/all] Error 2
    ```
  - Globalarrays and mumps suffer fortran type mismatch errors in division under GCC10+libtool:
    ```
    /bin/sh ./libtool  --tag=F77   --mode=compile /sw/peak/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-10.2.0/spectrum-mpi-10.4.0.0-20200604-6w55rca4u7ylcdprbldwkwm24whg7xyw/bin/mpifort -DHAVE_CONFIG_H -I.        -Ima -I./ma -I./LinAlg/lapack+blas -Iglobal/src -I./global/src -I./global/testing -I./pario/dra -I./pario/eaf -I./pario/elio -I./pario/sf   -Igaf2c -I./gaf2c -I./tcgmsg -I./tcgmsg/tcgmsg-mpi     -I./armci/src/include -I./armci/tcgmsg    -fdefault-integer-8 -fno-aggressive-loop-optimizations  -c -o ma/maf.lo ma/maf.F

    ma/maf.F:31:34:
    ...
    Error: Type mismatch between actual argument at (1) and actual argument at (2) (COMPLEX(4)/CHARACTER(*)).
ma/maf.F:41:35:

       29 |       if (f2c_inform_base(MT_BYTE, byte_mb(1), byte_mb(2)) .eq.
          |                                   2
    ......
       41 |       if (f2c_inform_base(MT_DCPL, dcpl_mb(1), dcpl_mb(2)) .eq.
          |                                   1
    Error: Type mismatch between actual argument at (1) and actual argument at (2) (COMPLEX(8)/CHARACTER(*)).
    make[2]: *** [Makefile:6758: ma/maf.lo] Error 1
    ```
    petsc and trilinos specs are removed due to this error in their
    dependency on mumps.
  - kvtree and it's dependents (veloc) are removed due to an issue of
    "multiple definition" errors when building kvtree tests:
    ```
    CMakeFiles/test_kvtree.dir/test_kvtree_allocate_delete.c.o:/tmp/belhorn/spack-stage/spack-stage-kvtree-1.0.2-u5au766n7zdum3kfd6ttpg7mvm3aawh5/spack-src/test/test_kvtree.h:20: multiple definition of `test_names'
    CMakeFiles/test_kvtree.dir/test_kvtree.c.o:/tmp/belhorn/spack-stage/spack-stage-kvtree-1.0.2-u5au766n7zdum3kfd6ttpg7mvm3aawh5/spack-src/test/test_kvtree.h:20: first defined here
    ```

On Andes:

- FFTW built with PGI is removed due to errors building for generic SIMD
  targets. The fix for this will likely require patching the automatic
  target optimization options in the FFTW spackage:
  ```
  PGC-S-0054-Subscript operator ([]) applied to non-array (../../../../simd-support/simd-generic128.h: 76)
  ...
  PGC-S-0073-Too many initializers for .P0002 (../../../../simd-support/simd-generic128.h: 148)
  ...
  PGC-F-0008-Error limit exceeded (../../../../simd-support/simd-generic128.h: 198)
  PGC/x86-64 Linux 19.10-0: compilation aborted
  ```